[project]
name = "marimo-publication"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.14.7",
    "pandas>=2.3.0",
    "plotly<6.0.0",
    "pyarrow>=20.0.0",
]
